name: Manual Bootstrap Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set script permissions
        run: chmod +x ./scripts/setup-ubuntu.sh ./scripts/setup-android-sdk.sh ./scripts/build-bootstraps.sh

      - name: Run setup-ubuntu.sh
        run: ./scripts/setup-ubuntu.sh

      - name: Run setup-android-sdk.sh
        run: ./scripts/setup-android-sdk.sh

      - name: Create symlink for /home/builder/termux-packages
        run: |
          sudo mkdir -p /home/builder
          sudo ln -s $GITHUB_WORKSPACE/termux-packages /home/builder/termux-packages

      - name: Build bootstraps
        run: ./scripts/build-bootstraps.sh --architectures "aarch64 arm i686 x86_64"

      - name: Upload bootstraps to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bootstraps
          path: bootstrap-*.zip
