name: Manual Bootstrap Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set script permissions
        run: chmod +x ./scripts/build-bootstraps.sh ./scripts/run-docker.sh

      - name: Run Bootstrap and Docker scripts
        run: |
          ./scripts/build-bootstraps.sh
          ./scripts/run-docker.sh
