name: Manual Bootstrap Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug list files
        run: |
          ls -al
          echo "In scripts folder:"
          ls -al scripts || echo "scripts folder not found"

      - name: Set script permissions
        run: chmod +x ./scripts/build-bootstrap.sh ./scripts/run-docker.sh

      - name: Run Bootstrap and Docker scripts
        run: |
          ./scripts/build-bootstrap.sh
          ./scripts/run-docker.sh
